export BUDGET=ai2/oe-training
export S3_BUCKET=ai2-llm
#export S3_PREFIX=preprocessed/olmo-mix/danyh-compiled-v1_7
#export S3_PREFIX=preprocessed/fastdclm
export S3_PREFIX=preprocessed/starcoder/v1-decon-100_to_20k-2star-top_token_030
export WEKA_BUCKET=oe-training-default
#export WEKA_PREFIX=ai2-llm/preprocessed/danyh-compiled-v1_7
#WEKA_PREFIX=ai2-llm/preprocessed/fastdclm
WEKA_PREFIX=ai2-llm/preprocessed/starcoder/v1-decon-100_to_20k-2star-top_token_030